package com.bookmap.api.rpc.server;

import com.bookmap.api.rpc.server.log.PythonLogger;
import com.bookmap.api.rpc.server.log.PythonStackTraceTracker;
import velox.api.layer1.common.Log;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * This is wrapper for logs received from extended systems which should be read and formatted in Bookmap way.
 * This class works asynchronously, so no need to worry about that main thread will be blocking. This instance of this class
 * are supposed to be used once for one input stream. After reading is finished, object can be released and can not be used again.
 */
public class LogTracker {

	// Bounded so we never wait forever for a hung Python process on shutdown, but long enough for a
	// destroyed process to actually close its pipes and unblock the readers.
	private static final int TERMINATION_TIMEOUT_SECONDS = 5;

	private static ExecutorService EXECUTOR_SERVICE;

	public static void track(Log.LogLevel logLevel, InputStream inputStream) {
		EXECUTOR_SERVICE.execute(() -> {
			try {
				PythonStackTraceTracker traceTracker = PythonStackTraceTracker.getTracker();
				try (var reader = new BufferedReader(new InputStreamReader(inputStream))) {
					String bufferLine;
					while ((bufferLine = reader.readLine()) != null) {
						switch (logLevel) {
							case INFO -> PythonLogger.info(bufferLine);
							case WARN -> PythonLogger.warn(bufferLine);
							case DEBUG -> PythonLogger.debug(bufferLine);
							case ERROR -> {
								PythonLogger.error(bufferLine);
								traceTracker.addErrorLine(bufferLine);
							}
							case TRADING -> PythonLogger.trade(bufferLine);
						}
					}
				} catch (IOException e) {
					Log.error("Failed to track logs from the stream", e);
				}
			} catch (Throwable t) {
				// Defensive: if this task is still running after the addon's classloader has already been
				// torn down (e.g. the Python process kept the pipe open past shutdown), loading any class
				// referenced below this point - including switch-map classes generated by the compiler -
				// fails with a raw ClassNotFoundException/NoClassDefFoundError. That is expected in this
				// narrow shutdown race, not a real bug, so it's logged here with full context instead of
				// bubbling up to Bookmap's global exception handler as an unexplained crash.
				String message = "Python log tracker thread (" + logLevel + ") stopped unexpectedly, likely during addon shutdown";
				if (t instanceof Exception) {
					Log.warn(message, (Exception) t);
				} else {
					Log.error(message, t);
				}
			}
		});
	}

	public static void initExecutorService() {
		AtomicInteger threadCount = new AtomicInteger();
		EXECUTOR_SERVICE = Executors.newCachedThreadPool(runnable -> {
			Thread thread = new Thread(runnable, "python-log-tracker-" + threadCount.incrementAndGet());
			thread.setDaemon(true);
			return thread;
		});
	}

	public static void finish() {
		if (EXECUTOR_SERVICE == null) {
			return;
		}
		EXECUTOR_SERVICE.shutdownNow();
		try {
			if (!EXECUTOR_SERVICE.awaitTermination(TERMINATION_TIMEOUT_SECONDS, TimeUnit.SECONDS)) {
				Log.warn("Python log tracker threads did not stop within " + TERMINATION_TIMEOUT_SECONDS
						+ "s, the Python process is likely still holding its output pipes open");
			}
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
		}
	}
}
